# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  products:
    image: products
    build:
      context: .
      dockerfile: src/Services/Products/Dockerfile
    ports:
      - "80"
      - "443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
