# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  MicroserviceBaseAppDb: 
    image: mongo

  products:
    image: products
    build:
      context: .
      dockerfile: src/Services/Products/Dockerfile
    ports:
      - 80
      - 443
