version: '3.4'

services:
  MicroserviceBaseAppDb:
    image: mongo
    
  products:
    image: ${DOCKER_REGISTRY-}microservicebaseappproducts
    build:
      context: .
      dockerfile: MicroserviceBaseApp.Products/Dockerfile
